### ISSUE TITLE
発見したバグ？

### ISSUE THREAD

**Issue by ghost** [TukamotoRyuzo/Yomita#1]
読み太バグ？
http://s1.gazo.cc/up/221575.jpg
読み筋が表示されない検討モード

**Comment by TukamotoRyuzo** [comment]
その局面は着手可能手が95玉の一手で、読み太は着手可能手が一手のときは探索せずにすぐにその手を指す仕様になっています。検討モードも例外ではなく、探索は行いません。
問題のある仕様とは思っていなかったのですが、検討モードの時のみ探索を行うような仕様も考えてみたいと思います。ご報告ありがとうございます。

**Comment by takachgay** [comment]
反応早くて驚きました
検討モードの場合候補手が出てもらわないと困りますのでね
候補手がmultiPVで指定しただけ表示されないと実用的ではありませんので、検討モードの場合も考慮して作っていただけると助かります。今回のmultiPV対応、お待ちしてました。
ちなみに最善手は９６歩ではないのでしょうか？

**Comment by takachgay** [comment]
反応早くて驚きました
検討モードの場合候補手が出てもらわないと困りますのでね
候補手がmultiPVで指定しただけ表示されないと実用的ではありませんので、検討モードの場合も考慮して作っていただけると助かります。今回のmultiPV対応、お待ちしてました。
ちなみに昨日の倉敷藤花で▲９６歩と里見さんが指した局面、読み太は９６歩を最善手と読みませんでしたが、最善手は９６歩ではないのでしょうか？

**Comment by takachgay** [comment]
http://s1.gazo.cc/up/221615.jpg
この局面の最善手は、何でしょうか？
開発社の人から見てどう思われますか？
浮かむ瀬は▲９６歩が最善手と出ます

**Comment by takachgay** [comment]
http://s1.gazo.cc/up/221615.jpg
この局面の最善手は、何でしょうか？
開発者の人から見てどう思われますか？
浮かむ瀬は▲９６歩が最善手と出ます

**Comment by takachgay** [comment]
ここの使い方分からない人が多いようなので、開発者様、twitterをしたらいかがでしょうか？
そうすれば要望やバグの報告なども伝えやすいかと思います

**Comment by TukamotoRyuzo** [comment]
10億局面ほど探索させましたが、96歩が最善と出ます。65馬と相当迷っているようですが、65馬同香96歩が読み筋なので、同じなのでしょうね。私も、96歩がよさそうに見えます。
twitterでの要望、バグの報告ですか。確かにgithubは英語でわかりずらいですよね。考えておきます。

**Comment by takachgay** [comment]
http://s1.gazo.cc/up/221628.jpg
multiPV２で検討モードの場合、９６歩が最善手と出てきません

**Comment by takachgay** [comment]
上記補足
yomita_kppt1.8.exeでの検討です

**Comment by TukamotoRyuzo** [comment]
multiPV2で探索させましたが、96歩と65馬が候補として表示されます。将棋所、ShogiGUIで試しましたが同じでした。ハッシュサイズが64MBの場合と8192MBの場合でも試しましたが関係ないようです。また、何回か試すと65馬の代わりに56金が候補に上がったりします。マルチスレッドで探索しているので、ある程度結果が揺れて96歩が第一候補に上がらないこともあるのではないでしょうか。これは仕方がないのかなと思います。

**Comment by takachgay** [comment]
３回位起動し直して検討しても私のパソコンでは９６歩が最善手と出ないのです
いつも上記の画像のように６５馬か５４桂馬なのです

**Comment by TukamotoRyuzo** [comment]
合法手が1手しかない時でも探索を行うように変更したバージョンをコミットしておきました。

>３回位起動し直して検討しても私のパソコンでは９６歩が最善手と出ないのです

すみませんが、そちらと条件を同じにしたいので、探索時のエンジン設定を教えていただいてもよろしいでしょうか。
byoyomi_margin 0, EvalDir eval/kppt_file/SDT4, Hash 8192, Draw_Score -50,など。

**Comment by takachgay** [comment]
http://s1.gazo.cc/up/221780.jpg
この設定です
今日の新バージョンはこれから入れます

**Comment by takachgay** [comment]
使用パソコンは
ウインドウズ８．１
i7-6700K メモリ32ギガ

**Comment by TukamotoRyuzo** [comment]
おそらく、評価関数バイナリが指定された場所(EvalDir)に入っていないのではないでしょうか。

**Comment by takachgay** [comment]
http://s1.gazo.cc/up/221782.jpg
１．８１検討画面

読み太をダウンロードして、そのまま検討モード使用してます
やねうら王とか入れてませんしフォルダもいじってません
だからですか

**Comment by TukamotoRyuzo** [comment]
Clone or downloadからダウンロードされたということでよろしいでしょうか。
その場合、評価関数は一緒にはダウンロードされないので、駒得のみの評価関数になってしまいます。

https://github.com/TukamotoRyuzo/Yomita/releases
こちらから
yomita_sdt4.zip
をダウンロードして、評価関数バイナリが入っているフォルダ(SDT4)を、指定のフォルダ(EvalDir)に配置することで解決するはずです。

**Comment by takachgay** [comment]
そうでしたかClone or downloadからダウンロードして使っていました
いまやってみますね

**Comment by ghost** [comment]
詰め合わせが一回でダウンロード出来ると便利ですね

**Comment by takachgay** [comment]
出来ました。お手数おかけしました

**Comment by takachgay** [comment]
http://s1.gazo.cc/up/221784.jpg
出来ました９６歩候補に出ました

**Comment by TukamotoRyuzo** [comment]
解決してよかったです。詰め合わせは、キリのよいところまで開発が進んだら作ろうと思っています。

**Comment by ghost** [comment]
お手数おかけしました

**Comment by TukamotoRyuzo** [comment]
いえいえ。報告ありがとうございました。
