### ISSUE TITLE
要望と質問

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#10]
要望
バージョンアップした場合、exeファイルだけ入れ替えれば（上書き）いいように出来れば便利なのですが。
バージョンアップの場合すべてをダウンロードして入れ替えねばなりませんか？
質問
ファイル名変えても動作しますか？（yomita_kppt2.01_sse42という名前を読みたとかyomita2.01とか）

**Comment by TukamotoRyuzo** [comment]
要望については、Gitを用いてこのリポジトリと同期を取れば差分だけを更新することが実現できますが、Gitを用いないのであれば難しいです。
ファイル名は変えても問題ありません
