### ISSUE TITLE
判明しているバグ

### ISSUE THREAD

**Issue by TukamotoRyuzo** [TukamotoRyuzo/Yomita#11]
2.02では置換表絡みのバグがあるようです。検討、対局の途中で例外が発生する可能性があります。すみません。

**Comment by job9876** [comment]
強さの変更がないと思い2.0からバージョンアップしてないのですが、2.02以降のバージョン出たら更新すれば宜しいですか？

**Comment by TukamotoRyuzo** [comment]
新バージョンは動作確認を行ってからコミットしてはいるものの、今回のようにコミットしてからバグが判明することもありますので、不安であれば更新はしなければよいと思います。

**Comment by TukamotoRyuzo** [comment]
動作確認を行った限りではバグは再現しなくなったので、このissueをcloseします。
