### ISSUE TITLE
更新について

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#12]
機能的な変更はありませんというのは、強さが変わってないという意味ですか？

**Comment by TukamotoRyuzo** [comment]
benchmarkコマンドというものがありまして、実行ファイルをダブルクリックしてbとタイプするとbenchmarkが始まるのですが、結果(探索ノード数)が前回のバージョンと変わらなければ、「機能的な変更はありません」という表記にしています。これはstockfishにならいました。強さは少なくとも1threadでは変わっていませんが、マルチスレッドならば変わっているかもしれません。
