### ISSUE TITLE
候補手や最善手が同じにならないソフト一致率

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#13]
同じ手をソフトが選ばないという現象は、あくまで早指しにおいてですよね？
長時間、10時間とか考えさせた場合最善手は常に同じになるのではないでしょうか？
同じ手になっていくと。

**Comment by TukamotoRyuzo** [comment]
同じ局面でも時によって違う指し手が最善手になるのはLazy SMPの性質なので、長時間でも最善手は変わると思います。
