### ISSUE TITLE
MultiPV

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#14]
MultiPVは検討モードで重要で将棋の大会には必要ないですかね？
MultiPV入れたほうが強くなりますか？

**Comment by TukamotoRyuzo** [comment]
実験してみないとなんともいえませんが、おそらく弱くなるでしょう。私はMultiPVは強さに全く関係がないオプションだと思っているので、読み太には最初は搭載しませんでした。大会でも使うつもりはないです。

**Comment by job9876** [comment]
最善手は１つだからですよね

**Comment by TukamotoRyuzo** [comment]
MultiPVを例えば2に設定すると、iteration毎の探索ノード数が倍になるので(厳密には何倍かわかりませんが)単純に探索効率が悪くなるからです。MultiPVを設定することで読み抜けが減る局面もありますがそういう局面は少ないので、結局MultiPVは設定しないほうが強いと思っています。
