### ISSUE TITLE
駒落ち将棋

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#16]
読み太は駒落ち将棋した場合（読み太が角を落とすなど）極端に実力が落ちるということはありますか？
平手のみ強いソフトとかあるのでしょうか？

**Comment by TukamotoRyuzo** [comment]
極端に実力が落ちることはないです。上位にいるソフトは平手はもちろん強いですが、例外なく駒落ちも強いと思いますよ。

**Comment by job9876** [comment]
ひとまず読み太の更新も終了ですか・・・
今後は、終盤力の克服できたソフトがponanzaに追いつくのでしょうか

**Comment by TukamotoRyuzo** [comment]
ponanzaが強いのは終盤だけではないので、終盤だけが強くなっても追いつかないでしょうね。
