### ISSUE TITLE
読み太の終盤

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#17]
とりあえず公開は５月世界大会まで停止ですか。読み太は使用しているやねうら王から終盤力がUPしているように思います。

**Comment by TukamotoRyuzo** [comment]
>とりあえず公開は５月世界大会まで停止ですか。

そうですね。現在は評価関数を色々いじって実験中です。

>読み太は使用しているやねうら王から終盤力がUPしているように思います。

そうなんですか？やねうら王との対局に限らずソフト同士の対局って、差がつくのはいつも中盤で、終盤にはほとんどの場合どちらかの圧倒的優勢で突入することが多く、あまり逆転が起こらないように見えます。終盤が強くなったかをどうやって判断すればよいのか、実は私はよくわかっていません。

**Comment by job9876** [comment]
手間がかかりますがプロの対局の棋譜を終盤他のソフトと並べ比べるしかないですね。

**Comment by TukamotoRyuzo** [comment]
なるほど。
手間がかかるので私としてはあまりやりたくない方法ではあります。
