### ISSUE TITLE
定跡使用しないで検討の場合の見解

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#18]
読み太で定跡使用せず検討した場合、この局面で先手有利と出ます。
▲７六歩      △３四歩      ▲２六歩      △８四歩      ▲２五歩      △８五歩
▲７八金      △３二金      ▲２四歩      △同　歩      ▲同　飛      △８六歩
▲同　歩      △同　飛      ▲３四飛      △３三角      ▲３六飛      △８四飛
▲２六飛      △２二銀      ▲８七歩      △７二銀      ▲５八玉      △１四歩
▲３三角成    △同　桂      ▲２一角      △４二玉      ▲３二角成    △同　玉
▲４二金      △２一玉      ▲２三歩      △１三銀
読み太の見解とは別として、読み太作者の人から見た形勢判断をお聞きしたいです。
（自分の見解では読み太と同じ先手良しと思いました）
追記
形勢判断だけじゃなく、最善手など棋譜の進行以外にあればお聞きしたいですね。

**Comment by TukamotoRyuzo** [comment]
駒得の後手を持ちたいです。この後の先手の具体的な攻めが見えません。

**Comment by job9876** [comment]
ではソフトの見解は間違いということですか。この手順ならばプロはソフトを嵌めて勝てますかね。

**Comment by TukamotoRyuzo** [comment]
ソフトで検討してみて少し意見が変わりました。ソフトによると先手が300くらいいいんですね。
この局面は後手がよさそうという意見は変わりませんが、ここから後手が優勢にするのは簡単ではなく、罠だらけです。先手は68銀と待ちますが、44角は46飛で角が成れず、24銀～12玉～23玉で良くなるというのが第一感でしたが先手も56飛車や77桂～65桂があり、かなりうるさいです。
後手の最善は44飛ではないかと思います。以下16歩35角36飛24角17桂35歩26飛25歩46飛45桂25桂42角13桂成同香55銀24飛45飛23飛46銀32玉28歩41玉77桂52玉がソフトとともに出した検討手順。ここまでくると先手+50くらいですが、先手に変化があるかもしれませんが、しっかり研究すれば勝てるかも知れません。

**Comment by job9876** [comment]
雑巾絞りというのを取り組んでるソフト開発者多いですが、読み太も雑巾絞りしているのですか？

**Comment by TukamotoRyuzo** [comment]
してますよ。

**Comment by job9876** [comment]
１．検討モードで、反則の手が棋譜にあった場合、正常に動作しますか？
例えば二歩や王が取られる位置に移動した場合の反則負けのプロの棋譜があった場合です。そういう場合、エラー出てソフトが落ちてしまうのか、何も表示されないとか、などです。

２．千日手の棋譜でエラー出るソフトもありますが千日手の棋譜も正常に動作しますか？
（千日手ですとか文字で表示される訳ではないでしょうけど）

**Comment by TukamotoRyuzo** [comment]
1はわかりません。が、将棋所は反則手を含む棋譜が入力された場合は反則手が入力される前の局面で止めてくれるようで、バグる心配はなさそうです。
2は、千日手の局面で検討モードにすると検討結果がすべて引き分け時のスコアになるという動作になっています。バグったりはしないようです。
