### ISSUE TITLE
選手権

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#19]
ぜひ読み太に５月の選手権で優勝して欲しいので、エビフライさんのくじらちゃんのようにクラスタ参加するシステムを読み太で作ったら協力したいと思っています。

**Comment by TukamotoRyuzo** [comment]
ありがとうございます！
クラスタは考えてませんでしたが、リモート参加の受付が3月31日までなので考えてみます。
クラスタで強くするより中身で強くしたいので、それまでに中身が十分強くできて余裕があったらの話ですが……

**Comment by job9876** [comment]
リモート参加は決意なさいましたか？

**Comment by TukamotoRyuzo** [comment]
今のところクラスタ部分はノータッチです。なかなかそこまで手が回らなくて。
一応、リモート参加の受け付けだけはしておこうと思います。
やる気が出たら実装するかもしれません。

**Comment by job9876** [comment]
yomita世界選手権はリモートしないならば、ノートパソコン1台で出場ですか

**Comment by TukamotoRyuzo** [comment]
そうです。

**Comment by TukamotoRyuzo** [comment]
クラスターにまで手が回らないと思ったので、リモート参加はしないことにしました。
期待させといてすみません。
本番まで頑張って中身を強くします。
