### ISSUE TITLE
検討で使用する場合、詰みの局面で候補手が表示されない時がある。

### ISSUE THREAD

**Issue by ghost** [TukamotoRyuzo/Yomita#2]
詰み発生の局面で候補手表記が１手も表示されない時があります。詰み手順が表示されません。内部で詰んでいるから終わっていると判断し表示する必要ないと判断しているようです。仕様なのでしょうが検討で使用する場合手順は必ず表示の方がいいと思います。

**Comment by TukamotoRyuzo** [comment]
ご報告ありがとうございます。
確かに、そういう仕様になっています。
対応はしばらくお待ちください。

**Comment by TukamotoRyuzo** [comment]
b93eb7e9390a9f3f2e818df234953842c5de89f2 にて上記問題に対応しました。
