### ISSUE TITLE
上位入賞を

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#20]
ゴールデンウイークの将棋ソフトの選手権終了後は読み太フリー公開しますか？
公開希望します。
読み太のノートパソコン１台での出場で入賞願っています。

**Comment by TukamotoRyuzo** [comment]
ありがとうございます！
選手権前に公開するかもしれません。

**Comment by job9876** [comment]
ぜひ、本家超えを、やねうら王さんは出場しませんが、ライブラリ本元のソフトを超えるソフトの出現を見たいですね。
