### ISSUE TITLE
入賞

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#21]
予想通りの入賞良かったです。
パソコン単体での実力はナンバー２くらいでしょうか。

**Comment by TukamotoRyuzo** [comment]
ありがとうございます！
正直入賞は難しいと思っていました。
パソコン単体でも読み太より強いソフトは7つはありました。

**Comment by job9876** [comment]
公開早いですね
起動してみました

**Comment by job9876** [comment]
読み太最新版にelmo評価関数入れてみたのですが、終盤力アップしたような印象です。ご自分でもお試し下さい。

**Comment by TukamotoRyuzo** [comment]
ありがとうございます。ちゃんと動いてるようですね。
elmo評価関数はまだ少ししか調べていませんが、読み太の評価関数と比べて思ったほど大きな差ではなかったという印象です。まだ少ないですが読み太評価関数 vs elmo評価関数で1手3秒1スレッドで39 - 2 - 51という成績です。
公開しているバージョンは王手延長がどうやらバグっているようです（なのに自己対戦では強くなっていたという）。しかし選手権に出したバージョンをそのまま出そうと思い、直さずにリリースしました。そのうち直そうと思います。

**Comment by job9876** [comment]
読み太はkppt_file内にWCSC27というフォルダを作ってbin入れると思っていたのですが、自分の好きな場所（フォルダ）にbin置いて指定しても動くのですか？

**Comment by TukamotoRyuzo** [comment]
好きな場所でいいですよ。
エンジン設定時に、Eval_Dirで評価関数バイナリが入ったフォルダを指定すればよいです。
もちろん、kppt_file内にWCSC27を作ってもいいですよ。
