### ISSUE TITLE
公開について

### ISSUE THREAD

**Issue by TukamotoRyuzo** [TukamotoRyuzo/Yomita#24]
ちょっとユーザー向けに修正したいところがあるので時間がかかります。USIオプション周りです。今週中には公開できるように頑張ります。公開を心待ちにしてくれている人がいたらすみません。あと、今回の評価関数バイナリは他のソフトでは使えないのでその辺は期待しないでください。

**Comment by TukamotoRyuzo** [comment]
公開しました。
今回はおそらく評価関数バイナリが大きいことが原因でx86用の実行バイナリを用意することが難しかったのですが、私が方法を知らないだけかもしれないのでもし知っている方がいれば教えてください。
またバグ報告等もこちらに書き込んでいただいてもかまいません。

**Comment by futukan** [comment]
いちから作った物のようで、評価値や候補手が既存のやねうら王ライブラリ系統ソフトと違って出ています

**Comment by TukamotoRyuzo** [comment]
それは不具合の報告でしょうか？

**Comment by futukan** [comment]
使ってみての感想です
動作は異常なしです

**Comment by TukamotoRyuzo** [comment]
わかりました。ありがとうございます。

**Comment by futukan** [comment]
![20171118152942](https://user-images.githubusercontent.com/33647537/32977665-708a78ca-cc75-11e7-9c70-b427f9380a24.jpg)
読み太で現在検討モード使用中です
これは３６飛車以下千日手ということになりますか？

**Comment by TukamotoRyuzo** [comment]
3六飛とした局面が過去に出現しているのならそうだと思います。局面付きで見せていただければ正確にお答えできるのですが。

**Comment by futukan** [comment]
やねうら王だと読み筋が千日手だと▲千日手と表示されます
形勢酷い局面だと▲劣等局面と表示される場合もあります

**Comment by TukamotoRyuzo** [comment]
それはバグではなく仕様の違いですので、追加してほしい機能の要望として聞いておきます。

**Comment by clammbon01** [comment]
ShogiGUIに取り込めないのですが

**Comment by TukamotoRyuzo** [comment]
調査します。報告ありがとうございます。

**Comment by TukamotoRyuzo** [comment]
こちらの環境ではShogiGUI version 0.0.6.11を使用して読み太を読み込めることは確認しました。
取り込めないというのはどういう状況か詳しく教えてもらえますか？

**Comment by clammbon01** [comment]
例えばelmoのsdt5には実行ファイルが含まれていないので
やねうら王の実行ファイルYaneuraOu-2017-early-sse42をelmoのフォルダに入れ、
ShogiGUI version 0.0.6.11の「ツール」→「エンジン設定」→エンジン一覧の「追加」を押し、
elmoのフォルダからやねうら王の実行ファイルをダブルクリックすると取り込まれますが、
yomita_engineフォルダ中の実行ファイルyomita_sse42をダブルクリックしても
「エンジンの起動に失敗しました」のエラーメッセージが出ます。（yomita_avx2でも同様）

**Comment by futukan** [comment]
clammbon01 さん
やねうら王に互換性がないので変換などしないと使えないです

**Comment by clammbon01** [comment]
例えが解りにくかったですか。
apery_sdt5の場合はフォルダ内の実行ファイルapery_sdt5_sse42をShogiGUI version 0.0.6.11で読み込めるのですが、yomita_engineの場合、フォルダ内の実行ファイルyomita_sse42をダブルクリックしても
「エンジンの起動に失敗しました」のエラーメッセージが出ます。

**Comment by ohga** [comment]
clammbon01 さん。
ShogiGUI に登録できない問題なのか、そもそもエンジンが動作していないのかを切り分けたいです。

エクスプローラーから yomita_sse42 のファイルを直接ダブルクリックし、黒い画面が表示されたら usi と打って改行してみて下さい。usiok と表示されない場合や、表示に時間がかかる場合は、なんらかの不具合、もしくはご利用の PC では動作しない可能性があります。

きちんと表示される場合はエンジンは動作しています。黒い画面は閉じてしまって構いません。
問題は ShogiGUI または、その設定の可能性があります。
例えば、将棋所で試していただくことは可能でしょうか？

**Comment by TukamotoRyuzo** [comment]
ohgaさん、代わりに答えてくださってありがとうございます。
そうですね、clammbon01さんはohgaさんの言われたことを試してもらえますか。

**Comment by clammbon01** [comment]
yomita_sse42 のファイルを直接ダブルクリックしてみたところ、黒い画面が出てきて、小文字のｓが表示されます（消去できません）。その後ろにusi と打って改行しても、ｓの下の行にusiと打って改行してもusiok とは表示されず、画面が消えます。
将棋所、試してみます。

**Comment by TukamotoRyuzo** [comment]
zipファイルをダウンロードしたあと、解凍しましたか？

**Comment by clammbon01** [comment]
将棋所で取り込めました。TukamotoRyuzo様、ohga様、ありがとうございました。

**Comment by ohga** [comment]
clammbon01 さん、ありがとうございます。
エンジン側の問題っぽいので、将棋所でも動作しない可能性が高いです。。

(勘ですが権限かなにかで io_log.txt あたりが出力できない、とかですかね？)
yomita_sse42 をデスクトップにコピーして、ファイルを直接ダブルクリックする、から試してもらえますか？

**Comment by ohga** [comment]
よかったです。
(たぶん 's' で止まるのは、io_log.txt の書き込み権限ですかね？、C ドライブ直下に置いて実行すると似た症状になる気がします)

**Comment by TukamotoRyuzo** [comment]
直ってよかったですね～。
zip圧縮した実行ファイルの動作はよくわからないです。
