### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by ghost** [TukamotoRyuzo/Yomita#3]
定跡が入っていますが、book.txtファイルを削除しても動作するように出来ていますか？
定跡を使用したくない場合は、book.txtファイルを削除すればいいのですか？
定跡を使用せずソフトに考えさせる使用法がしたいです。
>やねうら王、Aperyの評価関数バイナリは、読み太でも使うことができます。 付属している評価関数バイナリは、電王トーナメント時点ではやねうら王、Aperyでは使用できなかったのですが、 現在は使用できるようにしてあります。ただし、実験はしていません。
>
試してみましたが相互利用できました。aperyベースでyomita、yomitaベースでapery動作しました。やねうら王やSILENT_MAJORITYでは試してませんが浮かむ瀬で出来たので理論的に出来るはずです。
どの組み合わせのが最強なのかは試す気がありません。
yomita単体と、他ソフトのバイナリ組み合わせでも評価値の数値が違い出るけど候補手はどのソフトも一致する傾向にあります。同じ局面でも浮かむ瀬は評価値が過大に出る傾向にあるようです。

**Comment by TukamotoRyuzo** [comment]
定跡を使用したくない場合は、book.txtを実行ファイルがあるディレクトリに配置しなければよいです。
ただいちいち使う場合と使わない場合でそんなことをしなければならないと面倒なので、USIオプションでの対応を考えてみます。

>試してみましたが相互利用できました。aperyベースでyomita、yomitaベースでapery動作しました。

実験ありがとうございます。

**Comment by TukamotoRyuzo** [comment]
b93eb7e9390a9f3f2e818df234953842c5de89f2 にてUSIオプションでの定跡の使用/不使用の選択に対応しました。

**Comment by ghost** [comment]
1.82使ってみました、ShogiGUIの設定でmultiPVが1でも候補手が２つ出ます。multiPVの数値は１と２で挙動はどう違ってくるのでしょうか？

**Comment by ghost** [comment]
上記の設定は、SHOGIGUIの候補手の数を2手、エンジン登録の読み太のエンジン設定でmultiPVは１です

**Comment by ghost** [comment]
エンジン設定でUSIhashとhashの数値について。
この設定は２つとも同じ数値がいいのでしょうか？
hashの数値の方は低くても高くてもさほど変わらないようですが、最適な数値があればその数値にしたほうがいいかとは思いました。

**Comment by TukamotoRyuzo** [comment]
ShogiGUIの設定では、MultiPVと「候補手の数」の両方で候補手を何手求めるかを設定できるようで、「候補手の数」の設定が優先されるようです。なのでMultiPVは無視して「候補手の数」で設定を行ってください。
USI_Hashの値ですが、これは読み太では使っておらず、Hashの値が実際にメモリに確保されるハッシュのサイズになります。最適なサイズは、パソコンのメモリサイズの半分くらいがよいのではないでしょうか。

**Comment by ghost** [comment]
プロ（人間の対局）だと横歩取りで中住まいの５８玉から６８や４８へ王移動する時がありますが、ソフトは中央の位置のまま戦うのが基本で評価値高いです。
５８玉から６８や４８へ移動すると評価値下がったりします。人間の感覚とソフトの相違点です。
ソフトはバランス重視でそれが正しいのを人間が理解出来てないようです。

**Comment by ghost** [comment]
ソフト同士の対決では序盤中盤で読み勝ってリードしようというのが重要なのでしょうが、終盤力の強化こそが優勝できるソフトじゃないでしょうか。ponanzaや技巧の終盤力で逆転される事があります。
ponanza優勝続く理由は中盤や終盤の強さを実現してるからじゃないでしょうか。

**Comment by TukamotoRyuzo** [comment]
確かに終盤は弱点で、結構頓死します。
技巧は王手延長を工夫をして頓死を回避しているそうです。ponanzaはわかりませんが、詰め将棋ルーチンは積んでいると思います。
終盤を強化することで序中盤の読みが浅くなるという影響が出てしまうので、序中盤はそのままの強さで終盤だけを強くするというのは実は結構難しいことです。進行度で何とかできるかもしれませんが、その辺は要調整ですね。

**Comment by ghost** [comment]
検討モードで使用する事を想定した機能は1.82で実装完了ですね。

**Comment by TukamotoRyuzo** [comment]
そうですね。また何かあれば報告していただければありがたいです。
