### ISSUE TITLE
進行度について

### ISSUE THREAD

**Issue by ghost** [TukamotoRyuzo/Yomita#4]
初手から検討する場合と、局面編集で途中の局面から検討開始した場合。
同じ局面でも進行度の捉え方がどのように異なるのですか？
ソフトが強くなりソフト同士の大会では決着つくまで手数が長くなる傾向のようですが、256手引き分けのルールも改善する必要があるかもしれません。でないとどちらかが有利なのに引き分けになるケースも生じます

**Comment by TukamotoRyuzo** [comment]
>初手から検討する場合と、局面編集で途中の局面から検討開始した場合。
同じ局面でも進行度の捉え方がどのように異なるのですか？

どちらの場合でも進行度は同じです。評価関数と同じで局面単位で進行度を計算しており、その局面に至るまでの手順や手数の影響は受けません。

256手ルールは大会の運営スケジュール上必要だと思いますが、短いと言われればそうかもしれません。ただ、不利な将棋を256手まで粘って引き分けに持ち込むのもそれはそれで面白みがあると思っています。

**Comment by ghost** [comment]
>uuunuuun
@uuunuuun1さんtwitter
読み太1.8.1(やね評価関数) vs 浮かむ瀬を一手3秒で対局させてみました。読み太105-15-80 浮かむ(R差44)。対局数少ないですが浮かむ瀬を上回っている感じ。
>
現時点ではフリーソフト最強になったようです。

**Comment by TukamotoRyuzo** [comment]
そうですか。計測してくださった方に感謝。
ただ評価関数を借りてきての結果のようなので、ほとんど他力ですね。
評価関数も強化しなくては……。

**Comment by ghost** [comment]
持ち駒持っている場合、出来るだけ盤上の駒優先で攻めるとか、そのような考え方は必要でしょうか？

**Comment by TukamotoRyuzo** [comment]
必要かもしれませんが、わかりません。
現状だと駒を取る手と歩を成る手以外はすべて同格なので、駒打ちか否かで差をつけるべきかどうかは実験しないとなんとも。
