### ISSUE TITLE
設定について

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#6]
EvalShareの設定はオンとオフどちらがいいのですか？
説明してくださると助かります。

**Comment by TukamotoRyuzo** [comment]
複数起動しないのであればオフのほうがいいと思います。
EvalShareは、読み太を複数起動していてもメモリに読み込む評価関数バイナリを一つだけにするオプションで、メモリに読み込まれた評価関数バイナリを複数のプロセスから共有して使うことでメモリの消費を抑えることができます。自己対戦時に複数起動することがあるのでメモリの消費を抑えるために使っています。
