### ISSUE TITLE
時間による強さ

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#8]
3秒や10秒で強さ変わるというのはソフト同士に有効ですよね
では長時間検討に使用する場合だと3秒で強いように調整したものと、10秒で強いように調整したものがあったとして、その２つは1分（あるいは数十分）考えた場合、同じ様な強さになるのでしょうか？

**Comment by job9876** [comment]
今日新バージョン入れてみて使ってみたのですが（エンジン設定は前のバージョンと同じです、ハッシュやスレッド数）今までのバージョンがCPU使用率が８０％とかになったのが新バージョンは２７％くらいです（うちのパソコンだと浮かむ瀬ややねうら王も使ってると８０％くらいになります）
CPU使用率低いのは何か原因があるのではないでしょうか？

**Comment by job9876** [comment]
上記補足AVX2を使ってます。CPU使用率減ったということは、軽量化が実現できているならば問題ないでしょうが、極端に減ったので何かプログラム内で読み込めてないとかがあるのかと考えました。

**Comment by TukamotoRyuzo** [comment]
最初の質問ですが、10秒で強いように調整したもののほうが強いと私は考えています。自己対戦も基本的には長い時間での結果を信用する方針でやっています。
CPU使用率については、私の環境だと100%使ってくれています。すみませんがエンジン設定を教えていただけますか？

**Comment by job9876** [comment]
USIハッシュ１６３８４
USI　PONDER　false
USE　BOOK　false
スレッド数　８
これ以外は設定変更してません　初期設定のままmultiPV１のまま

**Comment by job9876** [comment]
変更した項目だけ書きます
ハッシュ１６３８４
USE　BOOK　false
USE　PONDER　false
スレッド数８

**Comment by job9876** [comment]
ハッシュ設定２つあって片方が１のままでしたので直したら問題なくなりましたので
この問題は解決でした

**Comment by TukamotoRyuzo** [comment]
ハッシュサイズが1だったとしてもCPU使用率には影響しないはずなのですが。
いずれにせよ解決したならよかったです。

**Comment by job9876** [comment]
それが変わったのですよね

**Comment by job9876** [comment]
最初Hash設定1、USI_Hash設定16384にしていました。そうしたらCPU使用率２７％でした。
そのあとHashサイズを16384に変更したらCPU使用率８０％くらいになりました。
動くから問題ないですが一応参考になるのならと思い書きました。
ですから影響あるようですね

**Comment by job9876** [comment]
動くから問題ないですが一応参考になるのならと思い書きました。

**Comment by job9876** [comment]
分かりにくい文章を書いてしまい申し訳ありませんでした。また疑問や要望あれば書き込ませて頂きます。

**Comment by TukamotoRyuzo** [comment]
いえいえ。また何かあれば報告していただけるとありがたいです。よろしくお願いします。
