### ISSUE TITLE
CPUスレッド設定初期値

### ISSUE THREAD

**Issue by job9876** [TukamotoRyuzo/Yomita#9]
読み太はスレッド数の初期値が１になってますけど、なぜでしょうか？
パソコンで仕事に使ってる時は４にして使ってます。仕事で使わないときは８にしてます。８だと重くなります。

**Comment by TukamotoRyuzo** [comment]
自己対戦するときは読み太を複数起動しますが、スレッド数の初期値が1でない場合自己対戦前の初期化時(setoption時)にスレッドの解体作業が発生し、その時にプログラムが落ちてしまうことがありました。なので初期値は1にしています。また初期値は1のほうがいきなりCPU使用率が100%になることがなく、よくわからないユーザにとっても安全かと思っています。
